/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-6g52vISbLhqx53We8y1a1asIhJCK5J9kly8WFbvTvOtyRdU2KMUXYel1q74XhBuinHy4uxKD-UPFhwpzw-UWdaryAq7OkIvY3EfOTfIeqDv3Wfju-GBvNwqy",
  "tt": "tt-1-ffG97BejYyVHmji0mnL7TZVLCmYDe2fcMY6xU3H88Ic=",
  "version": "2020-11-20"
}

export default ebconfig;